workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    environment:
      vars:
        APP_STORE_CONNECT_KEY_IDENTIFIER: $APP_STORE_CONNECT_KEY_IDENTIFIER
        APP_STORE_CONNECT_ISSUER_ID: $APP_STORE_CONNECT_ISSUER_ID
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.patou.makeyourbrain
        provisioning_profile: $CM_PROVISIONING_PROFILE
        certificate: $CM_CERTIFICATE
        certificate_password: $CM_CERTIFICATE_PASSWORD
    scripts:
      - name: Get Flutter packages
        script: |
          cd flutter_app
          flutter pub get
      - name: Build iOS
        script: |
          cd flutter_app
          flutter build ios --release --no-codesign
      - name: Build IPA
        script: |
          cd flutter_app
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme Runner
    artifacts:
      - flutter_app/build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true