workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    integrations:
      app_store_connect: Codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.patou.makeyourbrain
    scripts:
      - name: Get Flutter packages
        script: |
          cd flutter_app
          flutter pub get
      - name: Build iOS
        script: |
          cd flutter_app
          flutter build ios --release --no-codesign
      - name: Build IPA
        script: |
          cd flutter_app
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme Runner
    artifacts:
      - flutter_app/build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        use_signing_certificate: true
        submit_to_testflight: true